const DEFAULT_PRODUCTS=[{name:'Classic T-Shirt',category:'T-Shirts',price:399,image:'assets/tshirt.png',description:'Premium custom printed T-shirt.'},{name:'White Mug',category:'Mugs',price:199,image:'assets/white-mug.png',description:'Personalized photo/name mug.'},{name:'Black Mug',category:'Mugs',price:249,image:'assets/black-mug.png',description:'Premium black custom mug.'},{name:'Magic Mug',category:'Mugs',price:299,image:'assets/magic-mug.png',description:'Heat-reveal magic mug.'},{name:'Blue Mug',category:'Mugs',price:229,image:'assets/blue-mug.png',description:'Blue handle personalized mug.'},{name:'Water Bottle',category:'Bottles',price:349,image:'assets/water-bottle.png',description:'Custom printed water bottle.'},{name:'Marble Tile',category:'Tiles',price:299,image:'assets/marble-tile.png',description:'Personalized marble-look tile.'},{name:'Photo Tile',category:'Tiles',price:399,image:'assets/photo-tile.png',description:'Custom photo tile gift.'},{name:'Caps',category:'Caps',price:299,image:'assets/caps.png',description:'Custom printed cap.'},{name:'Plates',category:'Plates',price:399,image:'assets/plates.png',description:'Personalized decorative plate.'}];
let products=JSON.parse(localStorage.getItem('rw_products')||'null')||DEFAULT_PRODUCTS;const $=s=>document.querySelector(s);const save=()=>localStorage.setItem('rw_products',JSON.stringify(products));
function render(){const q=$('#search').value.toLowerCase(),cat=$('#catFilter').value;let list=products.map((p,i)=>({...p,i})).filter(p=>(cat==='All categories'||p.category===cat)&&(!q||p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q)));$('#count').textContent=products.length;$('#cats').textContent=new Set(products.map(p=>p.category)).size;$('#catFilter').innerHTML='<option>All categories</option>'+[...new Set(products.map(p=>p.category))].map(c=>`<option>${c}</option>`).join('');if(cat!=='All categories')$('#catFilter').value=cat;$('#table').innerHTML=list.map(p=>`<div class="product-row"><img src="${p.image}"><div><b>${p.name}</b><br><small>${p.category}</small></div><div>₹${Number(p.price).toLocaleString('en-IN')}</div><div><small>${p.description||''}</small></div><div class="row-actions"><button onclick="edit(${p.i})">Edit</button><button class="danger" onclick="removeProduct(${p.i})">Delete</button></div></div>`).join('')||'<p class="muted">No products found.</p>'}
window.edit=i=>{const p=products[i];$('#editIndex').value=i;$('#modalTitle').textContent='Edit product';$('#pname').value=p.name;$('#pcat').value=p.category;$('#pprice').value=p.price;$('#pimage').value=p.image;$('#pdesc').value=p.description||'';$('#editor').showModal()};window.removeProduct=i=>{if(confirm('Delete this product?')){products.splice(i,1);save();render()}};
$('#add').onclick=()=>{$('#editIndex').value='';$('#modalTitle').textContent='Add product';$('#productForm').reset();$('#editor').showModal()};$('#productForm').onsubmit=e=>{e.preventDefault();const p={name:$('#pname').value.trim(),category:$('#pcat').value.trim(),price:Number($('#pprice').value),image:$('#pimage').value.trim(),description:$('#pdesc').value.trim()};const i=$('#editIndex').value;i===''?products.push(p):products[Number(i)]=p;save();$('#editor').close();render()};$('#search').oninput=render;$('#catFilter').onchange=render;
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({products,settings:JSON.parse(localStorage.getItem('rw_settings')||'{}')},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rare-wear-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#saveSettings').onclick=()=>{localStorage.setItem('rw_settings',JSON.stringify({name:$('#bizName').value,phone:$('#bizPhone').value,instagram:$('#bizInstagram').value,address:$('#bizAddress').value,banner:$('#banner').value}));alert('Settings saved.');};
$('#loginForm').onsubmit=e=>{e.preventDefault();const email=$('#email').value,pass=$('#password').value;const configured=window.RARE_WEAR_CONFIG?.SUPABASE_URL&&window.RARE_WEAR_CONFIG?.SUPABASE_ANON_KEY;if(configured){const client=supabase.createClient(RARE_WEAR_CONFIG.SUPABASE_URL,RARE_WEAR_CONFIG.SUPABASE_ANON_KEY);client.auth.signInWithPassword({email,password}).then(({error})=>{if(error)alert(error.message);else showApp()})}else{if(pass!=='rare123')return alert('Local mode password is rare123. Change this before publishing.');showApp()}};function showApp(){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');render()};$('#logout').onclick=()=>location.reload();
const settings=JSON.parse(localStorage.getItem('rw_settings')||'{}');if(settings.name)$('#bizName').value=settings.name;if(settings.phone)$('#bizPhone').value=settings.phone;if(settings.instagram)$('#bizInstagram').value=settings.instagram;if(settings.address)$('#bizAddress').value=settings.address;if(settings.banner)$('#banner').value=settings.banner;
