const KEY="rareWearSiteDataV1";let data=null;
async function load(){try{const s=localStorage.getItem(KEY);if(s)data=JSON.parse(s);else{data=await (await fetch("assets/default-data.json")).json();localStorage.setItem(KEY,JSON.stringify(data));}}catch(e){alert("Could not load site data.")}}
function login(){const p=document.getElementById("loginPass").value;if(p===(data?.settings?.adminPassword||"rare123")){sessionStorage.setItem("rwAdmin","1");showDash()}else document.getElementById("loginErr").textContent="Incorrect password."}
function showDash(){document.getElementById("loginBox").classList.add("hidden");document.getElementById("dashboard").classList.remove("hidden");fill()}
function fill(){const s=data.settings;["brand","subbrand","phone","instagram","address","heroTitle","heroText","footerText"].forEach(k=>document.getElementById(k).value=s[k]||"");document.getElementById("adminPassword").value="";document.getElementById("bannerPreview").innerHTML=`<img src="${data.banner}" style="max-width:500px;width:100%;border-radius:10px;border:1px solid #333">`;renderProducts()}
function renderProducts(){const box=document.getElementById("productsAdmin");box.innerHTML=data.products.map((p,i)=>`<div class="product-admin"><img src="${p.image}" onerror="this.src='assets/logo.png'"><div><b>${esc(p.name)}</b><div style="color:#999;font-size:12px">${esc(p.category)} • ${p.price?("₹"+esc(p.price)):"Price on request"}</div></div><div class="actions"><button class="mini-btn" onclick="editProduct(${i})">Edit</button> <button class="mini-btn danger" onclick="deleteProduct(${i})">Delete</button></div></div>`).join("")}
function newProduct(){editProduct(-1)}
function editProduct(i){const p=i<0?{name:"",category:"T-Shirts",price:"",description:"",image:"assets/logo.png"}:data.products[i];const name=prompt("Product name:",p.name);if(name===null)return;const category=prompt("Category (T-Shirts, Mugs, Bottles, Tiles, Caps, Other):",p.category)||p.category;const price=prompt("Price (number only, leave blank for Price on request):",p.price||"");const desc=prompt("Short description:",p.description||"");const fileInput=document.createElement("input");fileInput.type="file";fileInput.accept="image/*";fileInput.onchange=()=>{if(fileInput.files[0])compressImage(fileInput.files[0],img=>{const np={...p,name,category,price,description:desc,image:img};if(i<0)data.products.push(np);else data.products[i]=np;persist();renderProducts()});};if(confirm("Do you want to choose/change the product photo? Click OK to choose a photo, Cancel to keep the current photo."))fileInput.click();else{const np={...p,name,category,price,description:desc};if(i<0)data.products.push(np);else data.products[i]=np;persist();renderProducts()}}
function deleteProduct(i){if(confirm("Delete "+data.products[i].name+"?")){data.products.splice(i,1);persist();renderProducts()}}
function persist(){localStorage.setItem(KEY,JSON.stringify(data))}
function saveAll(){const s=data.settings;["brand","subbrand","phone","instagram","address","heroTitle","heroText","footerText"].forEach(k=>s[k]=document.getElementById(k).value.trim());const np=document.getElementById("adminPassword").value.trim();if(np)s.adminPassword=np;persist();alert("Saved! Open View Website to see the changes.")}
document.getElementById("bannerFile").addEventListener("change",e=>{const f=e.target.files[0];if(f)compressImage(f,img=>{data.banner=img;document.getElementById("bannerPreview").innerHTML=`<img src="${img}" style="max-width:500px;width:100%;border-radius:10px">`;persist()})});
document.getElementById("importFile").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);persist();fill();alert("Backup imported.")}catch(err){alert("Invalid backup file.")}};r.readAsText(f)});
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="rare-wear-backup.json";a.click();URL.revokeObjectURL(a.href)}
async function resetData(){if(!confirm("Reset all website edits to the original demo data?"))return;data=await (await fetch("assets/default-data.json")).json();persist();fill();alert("Reset complete.")}
function compressImage(file,cb){const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1100,scale=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext("2d").drawImage(im,0,0,c.width,c.height);cb(c.toDataURL("image/jpeg",.82))};im.src=r.result};r.readAsDataURL(file)}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
(async()=>{await load();if(sessionStorage.getItem("rwAdmin")==="1")showDash()})();